var searchData = [
  [
    'q_0',
    ['q', ['../fr_8c.html#aba94275944de73c899dbeb5f987c82cd', 1, 'fr.c']],
  ],
  [
    'qlementine_20icons_1',
    [
      'Qlementine Icons',
      [
        '../md_node__modules_2_0diconify_2json_2collections.html#autotoc_md3551',
        1,
        '',
      ],
    ],
  ],
  [
    'qs_2',
    [
      'F.A.Qs',
      [
        '..//Users/vivi/astro/node_modules/@pkgjs/parseargs/README.md#autotoc_md5465',
        1,
        '',
      ],
    ],
  ],
  [
    'qs_20parse_3',
    [
      'qs.parse()',
      [
        '..//Users/vivi/astro/node_modules/querystringify/README.md#autotoc_md26760',
        1,
        '',
      ],
    ],
  ],
  [
    'qs_20stringify_4',
    [
      'qs.stringify()',
      [
        '..//Users/vivi/astro/node_modules/querystringify/README.md#autotoc_md26761',
        1,
        '',
      ],
    ],
  ],
  [
    'qué_20el_20archivo_20tt_20env_20tt_20no_20carga_20mis_20variables_20de_20entorno_20correctamente_5',
    [
      '¿Por qué el archivo &lt;tt&gt;.env&lt;/tt&gt; no carga mis variables de entorno correctamente?',
      [
        '../md_node__modules_2dotenv_2_r_e_a_d_m_e-es.html#autotoc_md12227',
        1,
        '',
      ],
    ],
  ],
  [
    'qué_20mis_20variables_20de_20entorno_20no_20aparecen_20para_20react_6',
    [
      '¿Por qué mis variables de entorno no aparecen para React?',
      [
        '../md_node__modules_2dotenv_2_r_e_a_d_m_e-es.html#autotoc_md12232',
        1,
        '',
      ],
    ],
  ],
  [
    'qualifiedattribute_20tt_7',
    [
      'qualifiedAttribute tt',
      [
        '../md_node__modules_2eslint-plugin-astro_2node__modules_2postcss-selector-parser_2_a_p_i.html#autotoc_md13074',
        1,
        '&lt;tt&gt;attribute.qualifiedAttribute&lt;/tt&gt;',
      ],
      [
        '../md_node__modules_2postcss-selector-parser_2_a_p_i.html#autotoc_md26140',
        1,
        '&lt;tt&gt;attribute.qualifiedAttribute&lt;/tt&gt;',
      ],
    ],
  ],
  [
    'quantifiers_8',
    [
      'Quantifiers',
      [
        '..//Users/vivi/astro/node_modules/regexp-tree/README.md#autotoc_md28611',
        1,
        '',
      ],
    ],
  ],
  [
    'quantifiers_9',
    [
      'quantifiers',
      [
        '..//Users/vivi/astro/node_modules/braces/README.md#autotoc_md9577',
        1,
        'options.quantifiers',
      ],
      [
        '..//Users/vivi/astro/node_modules/oniguruma-to-es/node_modules/regex/README.md#autotoc_md25147',
        1,
        'Possessive quantifiers',
      ],
      [
        '..//Users/vivi/astro/node_modules/regex/README.md#autotoc_md28543',
        1,
        'Possessive quantifiers',
      ],
      [
        '..//Users/vivi/astro/node_modules/regexp-tree/README.md#autotoc_md28615',
        1,
        'Range-based quantifiers',
      ],
    ],
  ],
  [
    'quantile_20scales_10',
    [
      'Quantile Scales',
      [
        '..//Users/vivi/astro/node_modules/d3-scale/README.md#autotoc_md11252',
        1,
        '',
      ],
    ],
  ],
  [
    'quantity_11',
    [
      'valueParser.unit(quantity)',
      [
        '..//Users/vivi/astro/node_modules/postcss-value-parser/README.md#autotoc_md26229',
        1,
        '',
      ],
    ],
  ],
  [
    'quantize_20scales_12',
    [
      'Quantize Scales',
      [
        '..//Users/vivi/astro/node_modules/d3-scale/README.md#autotoc_md11251',
        1,
        '',
      ],
    ],
  ],
  [
    'que_20ya_20estaban_20configuradas_13',
    [
      '¿Qué sucede con las variables de entorno que ya estaban configuradas?',
      [
        '../md_node__modules_2dotenv_2_r_e_a_d_m_e-es.html#autotoc_md12231',
        1,
        '',
      ],
    ],
  ],
  [
    'queries_14',
    [
      'OpenSearch Queries',
      ['../md_src_2docs_2guides_2monitoring.html#autotoc_md37239', 1, ''],
    ],
  ],
  [
    'queries_15',
    [
      'GraphQL API queries',
      [
        '..//Users/vivi/astro/node_modules/octokit/README.md#autotoc_md25058',
        1,
        '',
      ],
    ],
  ],
  [
    'query_16',
    [
      'Send a simple query',
      [
        '..//Users/vivi/astro/node_modules/@octokit/graphql/README.md#autotoc_md5239',
        1,
        '',
      ],
    ],
  ],
  [
    'query_20and_20the_20request_20body_17',
    [
      'query and the request body',
      [
        '..//Users/vivi/astro/node_modules/@octokit/endpoint/README.md#autotoc_md5235',
        1,
        'Set parameters for both the URL/query and the request body',
      ],
      [
        '..//Users/vivi/astro/node_modules/@octokit/request/README.md#autotoc_md5366',
        1,
        'Set parameters for both the URL/query and the request body',
      ],
    ],
  ],
  [
    'query_20change_20log_18',
    [
      'aria-query Change Log',
      [
        '../md_node__modules_2_0dtesting-library_2dom_2node__modules_2aria-query_2_c_h_a_n_g_e_l_o_g.html',
        1,
        '',
      ],
    ],
  ],
  [
    'query_20example_19',
    [
      'Query Example',
      [
        '..//Users/vivi/astro/node_modules/jsonpath/README.md#autotoc_md21243',
        1,
        '',
      ],
    ],
  ],
  [
    'query_20obj_20pathexpression_20count_20',
    [
      'jp.query(obj, pathExpression[, count])',
      [
        '..//Users/vivi/astro/node_modules/jsonpath/README.md#autotoc_md21247',
        1,
        '',
      ],
    ],
  ],
  [
    'query_20parser_20v0_202_203_21',
    [
      'postcss-media-query-parser@v0.2.3',
      [
        '../md_tests_2security_2node__modules_2_8pnpm_2prettier_0d3_85_83_2node__modules_2prettier_2_t_h_i_r_d-_p_a_r_t_y-_n_o_t_i_c_e_s.html#autotoc_md38111',
        1,
        '',
      ],
    ],
  ],
  [
    'query_20search_20params_22',
    [
      '✔️ Adding Query Search Params',
      [
        '..//Users/vivi/astro/node_modules/ofetch/README.md#autotoc_md25079',
        1,
        '',
      ],
    ],
  ],
  [
    'query_20together_20with_20headers_20and_20variables_23',
    [
      'Pass query together with headers and variables',
      [
        '..//Users/vivi/astro/node_modules/@octokit/graphql/README.md#autotoc_md5242',
        1,
        '',
      ],
    ],
  ],
  [
    'query_20tt_24',
    [
      'query tt',
      [
        '..//Users/vivi/astro/node_modules/electron-to-chromium/README.md#autotoc_md12363',
        1,
        '&lt;tt&gt;chromiumToElectron(query)&lt;/tt&gt;',
      ],
      [
        '..//Users/vivi/astro/node_modules/electron-to-chromium/README.md#autotoc_md12362',
        1,
        '&lt;tt&gt;electronToChromium(query)&lt;/tt&gt;',
      ],
      [
        '..//Users/vivi/astro/node_modules/ufo/README.md#autotoc_md33966',
        1,
        '&lt;tt&gt;stringifyQuery(query)&lt;/tt&gt;',
      ],
      [
        '..//Users/vivi/astro/node_modules/ufo/README.md#autotoc_md33995',
        1,
        '&lt;tt&gt;withQuery(input, query)&lt;/tt&gt;',
      ],
      [
        '..//Users/vivi/astro/node_modules/@neondatabase/serverless/README.md#autotoc_md5026',
        1,
        'Example: Vercel Edge Function with &lt;tt&gt;Pool.query()&lt;/tt&gt;',
      ],
    ],
  ],
  [
    'query_20tt_20strong_20deprecated_20strong_25',
    [
      '&lt;tt&gt;electronToBrowserList(query)&lt;/tt&gt; &lt;strong&gt;DEPRECATED&lt;/strong&gt;',
      [
        '..//Users/vivi/astro/node_modules/electron-to-chromium/README.md#autotoc_md12364',
        1,
        '',
      ],
    ],
  ],
  [
    'query_20utils_26',
    [
      'Query Utils',
      [
        '..//Users/vivi/astro/node_modules/ufo/README.md#autotoc_md33963',
        1,
        '',
      ],
    ],
  ],
  [
    'query_20workflow_203abrowser_20img_20src_20https_3a_20github_20com_20uuidjs_20uuid_20workflows_20browser_20badge_20svg_20alt_20browser_20a_27',
    [
      'uuid &lt;a href=&quot;https://github.com/uuidjs/uuid/actions?query=workflow%3ACI&quot; &gt;&lt;img src=&quot;https://github.com/uuidjs/uuid/workflows/CI/badge.svg&quot; alt=&quot;CI&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://github.com/uuidjs/uuid/actions?query=workflow%3ABrowser&quot; &gt;&lt;img src=&quot;https://github.com/uuidjs/uuid/workflows/Browser/badge.svg&quot; alt=&quot;Browser&quot;/&gt;&lt;/a&gt;',
      [
        '..//Users/vivi/astro/node_modules/uuid/README.md#autotoc_md34624',
        1,
        '',
      ],
    ],
  ],
  [
    'query_20workflow_203aci_20img_20src_20https_3a_20github_20com_20uuidjs_20uuid_20workflows_20ci_20badge_20svg_20alt_20ci_20a_20a_20href_20https_3a_20github_20com_20uuidjs_20uuid_20actions_20query_20workflow_203abrowser_20img_20src_20https_3a_20github_20com_20uuidjs_20uuid_20workflows_20browser_20badge_20svg_20alt_20browser_20a_28',
    [
      'uuid &lt;a href=&quot;https://github.com/uuidjs/uuid/actions?query=workflow%3ACI&quot; &gt;&lt;img src=&quot;https://github.com/uuidjs/uuid/workflows/CI/badge.svg&quot; alt=&quot;CI&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://github.com/uuidjs/uuid/actions?query=workflow%3ABrowser&quot; &gt;&lt;img src=&quot;https://github.com/uuidjs/uuid/workflows/Browser/badge.svg&quot; alt=&quot;Browser&quot;/&gt;&lt;/a&gt;',
      [
        '..//Users/vivi/astro/node_modules/uuid/README.md#autotoc_md34624',
        1,
        '',
      ],
    ],
  ],
  [
    'query_5fllm_29',
    [
      'query_llm',
      [
        '../namespacellm__api.html#aadf2ecf7c23bfd87d01deb281d09f02b',
        1,
        'llm_api',
      ],
    ],
  ],
  [
    'query_5fllm_5fwith_5fplan_30',
    [
      'query_llm_with_plan',
      [
        '../namespaceplan__exec__llm.html#a893c9f38ecfef0372e2c0404d8817a06',
        1,
        'plan_exec_llm',
      ],
    ],
  ],
  [
    'queryfn_20force_20tt_31',
    [
      '&lt;tt&gt;var removeListener = siginfo(queryFn, [force])&lt;/tt&gt;',
      [
        '..//Users/vivi/astro/node_modules/siginfo/README.md#autotoc_md30718',
        1,
        '',
      ],
    ],
  ],
  [
    'querying_32',
    [
      'Querying',
      [
        '..//Users/vivi/astro/node_modules/@vercel/postgres/README.md#autotoc_md7202',
        1,
        '',
      ],
    ],
  ],
  [
    'querying_20data_20in_20redis_20hashes_33',
    [
      'Indexing and Querying Data in Redis Hashes',
      [
        '..//Users/vivi/astro/node_modules/@redis/search/README.md#autotoc_md5612',
        1,
        '',
      ],
    ],
  ],
  [
    'querying_20data_20with_20redisjson_34',
    [
      'Indexing and Querying Data with RedisJSON',
      [
        '..//Users/vivi/astro/node_modules/@redis/search/README.md#autotoc_md5615',
        1,
        '',
      ],
    ],
  ],
  [
    'querying_20the_20index_35',
    [
      'Querying the Index',
      [
        '..//Users/vivi/astro/node_modules/@redis/search/README.md#autotoc_md5614',
        1,
        'Querying the Index',
      ],
      [
        '..//Users/vivi/astro/node_modules/@redis/search/README.md#autotoc_md5617',
        1,
        'Querying the Index',
      ],
    ],
  ],
  [
    'question_36',
    [
      'Question',
      [
        '..//Users/vivi/astro/node_modules/inquirer/README.md#autotoc_md18153',
        1,
        '',
      ],
    ],
  ],
  [
    'question_20conditionally_37',
    [
      'Ask a question conditionally',
      [
        '..//Users/vivi/astro/node_modules/@inquirer/prompts/README.md#autotoc_md3791',
        1,
        '',
      ],
    ],
  ],
  [
    'questions_38',
    [
      'Questions',
      [
        '..//Users/vivi/astro/node_modules/@testing-library/react/README.md#autotoc_md6413',
        1,
        '❓ Questions',
      ],
      [
        '..//Users/vivi/astro/node_modules/@testing-library/user-event/README.md#autotoc_md6422',
        1,
        '❓ Questions',
      ],
      [
        '..//Users/vivi/astro/node_modules/doctrine/README.md#autotoc_md12016',
        1,
        'Frequently Asked Questions',
      ],
      [
        '..//Users/vivi/astro/node_modules/eslint-plugin-react/node_modules/doctrine/README.md#autotoc_md14133',
        1,
        'Frequently Asked Questions',
      ],
      [
        '..//Users/vivi/astro/node_modules/eslint/README.md#autotoc_md14447',
        1,
        'Frequently Asked Questions',
      ],
      [
        '..//Users/vivi/astro/node_modules/espree/README.md#autotoc_md14483',
        1,
        'Frequently Asked Questions',
      ],
      [
        '..//Users/vivi/astro/node_modules/jsonc-eslint-parser/node_modules/espree/README.md#autotoc_md21169',
        1,
        'Frequently Asked Questions',
      ],
      [
        '..//Users/vivi/astro/node_modules/lint-staged/README.md#autotoc_md21845',
        1,
        'Frequently Asked Questions',
      ],
      [
        '..//Users/vivi/astro/tests/security/node_modules/.pnpm/eslint@9.22.0/node_modules/eslint/README.md#autotoc_md37884',
        1,
        'Frequently Asked Questions',
      ],
    ],
  ],
  [
    'questions_20and_20issues_39',
    [
      'Questions and issues',
      [
        '..//Users/vivi/astro/node_modules/bluebird/README.md#autotoc_md9434',
        1,
        '',
      ],
    ],
  ],
  [
    'questions_20answers_20promise_20tt_40',
    [
      '&lt;tt&gt;inquirer.prompt(questions, answers) -\&gt; promise&lt;/tt&gt;',
      [
        '..//Users/vivi/astro/node_modules/inquirer/README.md#autotoc_md18149',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_41',
    [
      'Offline Queue',
      [
        '..//Users/vivi/astro/node_modules/ioredis/README.md#autotoc_md18223',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_42',
    [
      'queue',
      [
        '..//Users/vivi/astro/node_modules/p-queue/readme.md#autotoc_md25405',
        1,
        'queue',
      ],
      [
        '../md_node__modules_2vitest_2_l_i_c_e_n_s_e.html#autotoc_md35221',
        1,
        'yocto-queue',
      ],
    ],
  ],
  [
    'queue_20concurrency_43',
    [
      'queue.concurrency',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15267',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20drain_44',
    [
      'queue.drain',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15271',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20drained_20promise_45',
    [
      'queue.drained() =&gt; Promise',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15280',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20empty_46',
    [
      'queue.empty',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15273',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20error_20handler_47',
    [
      'queue.error(handler)',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15265',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20getqueue_48',
    [
      'queue.getQueue()',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15259',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20idle_49',
    [
      'queue.idle()',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15255',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20kill_50',
    [
      'queue.kill()',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15261',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20killanddrain_51',
    [
      'queue.killAndDrain()',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15263',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20length_52',
    [
      'queue.length()',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15257',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20microtask_20v1_202_203_53',
    [
      'queue-microtask@v1.2.3',
      [
        '../md_tests_2security_2node__modules_2_8pnpm_2prettier_0d3_85_83_2node__modules_2prettier_2_t_h_i_r_d-_p_a_r_t_y-_n_o_t_i_c_e_s.html#autotoc_md38121',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20new_20queue_20tt_54',
    [
      'queue new Queue tt',
      [
        '..//Users/vivi/astro/node_modules/p-limit/node_modules/yocto-queue/readme.md#autotoc_md25342',
        1,
        '&lt;tt&gt;queue = new Queue()&lt;/tt&gt;',
      ],
      [
        '..//Users/vivi/astro/node_modules/yocto-queue/readme.md#autotoc_md36256',
        1,
        '&lt;tt&gt;queue = new Queue()&lt;/tt&gt;',
      ],
    ],
  ],
  [
    'queue_20pause_55',
    [
      'queue.pause()',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15251',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20paused_56',
    [
      'queue.paused',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15269',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20push_20task_20done_57',
    [
      'queue.push(task, done)',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15247',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20push_20task_20promise_58',
    [
      'queue.push(task) =&gt; Promise',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15278',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20resume_59',
    [
      'queue.resume()',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15253',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20saturated_60',
    [
      'queue.saturated',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15275',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20tt_61',
    [
      'Queue tt',
      [
        '..//Users/vivi/astro/node_modules/p-limit/node_modules/yocto-queue/readme.md#autotoc_md25342',
        1,
        '&lt;tt&gt;queue = new Queue()&lt;/tt&gt;',
      ],
      [
        '..//Users/vivi/astro/node_modules/yocto-queue/readme.md#autotoc_md36256',
        1,
        '&lt;tt&gt;queue = new Queue()&lt;/tt&gt;',
      ],
    ],
  ],
  [
    'queue_20tt_20a_20package_62',
    [
      'queue tt a package',
      [
        '..//Users/vivi/astro/node_modules/astro/node_modules/p-limit/readme.md#autotoc_md8375',
        1,
        'How is this different from the &lt;a href=&quot;https://github.com/sindresorhus/p-queue&quot; &gt;&lt;tt&gt;p-queue&lt;/tt&gt;&lt;/a&gt; package?',
      ],
      [
        '..//Users/vivi/astro/node_modules/find-up/node_modules/p-limit/readme.md#autotoc_md15550',
        1,
        'How is this different from the &lt;a href=&quot;https://github.com/sindresorhus/p-queue&quot; &gt;&lt;tt&gt;p-queue&lt;/tt&gt;&lt;/a&gt; package?',
      ],
      [
        '..//Users/vivi/astro/node_modules/p-limit/readme.md#autotoc_md25361',
        1,
        'How is this different from the &lt;a href=&quot;https://github.com/sindresorhus/p-queue&quot; &gt;&lt;tt&gt;p-queue&lt;/tt&gt;&lt;/a&gt; package?',
      ],
    ],
  ],
  [
    'queue_20tt_20p_20queue_20tt_20a_20package_63',
    [
      'queue tt p queue tt a package',
      [
        '..//Users/vivi/astro/node_modules/astro/node_modules/p-limit/readme.md#autotoc_md8375',
        1,
        'How is this different from the &lt;a href=&quot;https://github.com/sindresorhus/p-queue&quot; &gt;&lt;tt&gt;p-queue&lt;/tt&gt;&lt;/a&gt; package?',
      ],
      [
        '..//Users/vivi/astro/node_modules/find-up/node_modules/p-limit/readme.md#autotoc_md15550',
        1,
        'How is this different from the &lt;a href=&quot;https://github.com/sindresorhus/p-queue&quot; &gt;&lt;tt&gt;p-queue&lt;/tt&gt;&lt;/a&gt; package?',
      ],
      [
        '..//Users/vivi/astro/node_modules/p-limit/readme.md#autotoc_md25361',
        1,
        'How is this different from the &lt;a href=&quot;https://github.com/sindresorhus/p-queue&quot; &gt;&lt;tt&gt;p-queue&lt;/tt&gt;&lt;/a&gt; package?',
      ],
    ],
  ],
  [
    'queue_20unshift_20task_20done_64',
    [
      'queue.unshift(task, done)',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15249',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20unshift_20task_20promise_65',
    [
      'queue.unshift(task) =&gt; Promise',
      [
        '..//Users/vivi/astro/node_modules/fastq/README.md#autotoc_md15279',
        1,
        '',
      ],
    ],
  ],
  [
    'queue_20v1_201_201_66',
    [
      'yocto-queue@v1.1.1',
      [
        '../md_tests_2security_2node__modules_2_8pnpm_2prettier_0d3_85_83_2node__modules_2prettier_2_t_h_i_r_d-_p_a_r_t_y-_n_o_t_i_c_e_s.html#autotoc_md38202',
        1,
        '',
      ],
    ],
  ],
  [
    'queueclass_67',
    [
      'Custom QueueClass',
      [
        '..//Users/vivi/astro/node_modules/p-queue/readme.md#autotoc_md25435',
        1,
        '',
      ],
    ],
  ],
  [
    'queueclass_68',
    [
      'queueClass',
      [
        '..//Users/vivi/astro/node_modules/p-queue/readme.md#autotoc_md25401',
        1,
        '',
      ],
    ],
  ],
  [
    'queued_69',
    [
      'queued()',
      [
        '..//Users/vivi/astro/node_modules/bottleneck/README.md#autotoc_md9468',
        1,
        '',
      ],
    ],
  ],
  [
    'queuedrain_20function_70',
    [
      'mergedStream.on(&apos;queueDrain&apos;, function() {})',
      [
        '..//Users/vivi/astro/node_modules/merge2/README.md#autotoc_md23107',
        1,
        '',
      ],
    ],
  ],
  [
    'queueing_71',
    [
      'Priority Queueing',
      [
        '..//Users/vivi/astro/node_modules/generic-pool/README.md#autotoc_md16025',
        1,
        '',
      ],
    ],
  ],
  [
    'queuemicrotask_20fn_20tt_72',
    [
      '&lt;tt&gt;queueMicrotask(fn)&lt;/tt&gt;',
      [
        '..//Users/vivi/astro/node_modules/queue-microtask/README.md#autotoc_md26774',
        1,
        '',
      ],
    ],
  ],
  [
    'queuemicrotask_20tt_20a_20shim_20for_20modern_20engines_73',
    [
      'fast, tiny &lt;a href=&quot;https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/queueMicrotask&quot; &gt;&lt;tt&gt;queueMicrotask&lt;/tt&gt;&lt;/a&gt; shim for modern engines',
      [
        '..//Users/vivi/astro/node_modules/queue-microtask/README.md#autotoc_md26764',
        1,
        '',
      ],
    ],
  ],
  [
    'queuemicrotask_20tt_20and_20why_20would_20one_20use_20it_74',
    [
      'What is &lt;tt&gt;queueMicrotask&lt;/tt&gt; and why would one use it?',
      [
        '..//Users/vivi/astro/node_modules/queue-microtask/README.md#autotoc_md26767',
        1,
        '',
      ],
    ],
  ],
  [
    'queuemicrotask_20tt_20queuemicrotask_20tt_20a_20shim_20for_20modern_20engines_75',
    [
      'fast, tiny &lt;a href=&quot;https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/queueMicrotask&quot; &gt;&lt;tt&gt;queueMicrotask&lt;/tt&gt;&lt;/a&gt; shim for modern engines',
      [
        '..//Users/vivi/astro/node_modules/queue-microtask/README.md#autotoc_md26764',
        1,
        '',
      ],
    ],
  ],
  [
    'quick_20example_76',
    [
      'Quick Example',
      [
        '..//Users/vivi/astro/node_modules/imurmurhash/README.md#autotoc_md18100',
        1,
        '',
      ],
    ],
  ],
  [
    'quick_20examples_77',
    [
      'Quick Examples',
      [
        '..//Users/vivi/astro/node_modules/escodegen/node_modules/levn/README.md#autotoc_md12809',
        1,
        'Quick Examples',
      ],
      [
        '..//Users/vivi/astro/node_modules/escodegen/node_modules/type-check/README.md#autotoc_md12882',
        1,
        'Quick Examples',
      ],
      [
        '..//Users/vivi/astro/node_modules/eslint/node_modules/type-check/README.md#autotoc_md14419',
        1,
        'Quick Examples',
      ],
      [
        '..//Users/vivi/astro/node_modules/levn/node_modules/type-check/README.md#autotoc_md21551',
        1,
        'Quick Examples',
      ],
      [
        '..//Users/vivi/astro/node_modules/levn/README.md#autotoc_md21572',
        1,
        'Quick Examples',
      ],
      [
        '..//Users/vivi/astro/node_modules/optionator/node_modules/levn/README.md#autotoc_md25212',
        1,
        'Quick Examples',
      ],
      [
        '..//Users/vivi/astro/node_modules/type-check/README.md#autotoc_md33808',
        1,
        'Quick Examples',
      ],
    ],
  ],
  [
    'quick_20installation_78',
    [
      'Quick Installation',
      [
        '..//Users/vivi/astro/node_modules/@fontsource/dm-mono/README.md#autotoc_md3388',
        1,
        'Quick Installation',
      ],
      [
        '..//Users/vivi/astro/node_modules/@fontsource/inter/README.md#autotoc_md3393',
        1,
        'Quick Installation',
      ],
      [
        '..//Users/vivi/astro/node_modules/@fontsource/roboto-condensed/README.md#autotoc_md3398',
        1,
        'Quick Installation',
      ],
    ],
  ],
  [
    'quick_20migration_79',
    [
      'Quick Migration',
      ['../md_node__modules_2chai_2_release_notes.html#autotoc_md9966', 1, ''],
    ],
  ],
  [
    'quick_20overview_80',
    [
      'Migration Quick Overview',
      [
        '../md_node__modules_2flexsearch_2_c_h_a_n_g_e_l_o_g.html#autotoc_md15640',
        1,
        '',
      ],
    ],
  ],
  [
    'quick_20response_20guide_81',
    [
      'Quick Response Guide',
      [
        '../md_src_2docs_2deployment_2disaster-recovery.html#autotoc_md37141',
        1,
        '',
      ],
    ],
  ],
  [
    'quick_20start_82',
    [
      'Quick Start',
      [
        '..//Users/vivi/astro/node_modules/ofetch/README.md#autotoc_md25070',
        1,
        '🚀 Quick Start',
      ],
      [
        '..//Users/vivi/astro/node_modules/@shadcn/ui/node_modules/commander/Readme.md#autotoc_md5718',
        1,
        'Quick Start',
      ],
      [
        '..//Users/vivi/astro/node_modules/@upstash/redis/README.md#autotoc_md7134',
        1,
        'Quick Start',
      ],
      [
        '..//Users/vivi/astro/node_modules/@vercel/postgres/README.md#autotoc_md7199',
        1,
        'Quick Start',
      ],
      [
        '..//Users/vivi/astro/node_modules/bottleneck/README.md#autotoc_md9441',
        1,
        'Quick Start',
      ],
      [
        '..//Users/vivi/astro/node_modules/denque/README.md#autotoc_md11782',
        1,
        'Quick Start',
      ],
      [
        '..//Users/vivi/astro/node_modules/eslint-plugin-astro/node_modules/postcss-selector-parser/README.md#autotoc_md13150',
        1,
        'Quick Start',
      ],
      [
        '..//Users/vivi/astro/node_modules/ioredis/README.md#autotoc_md18202',
        1,
        'Quick Start',
      ],
      [
        '..//Users/vivi/astro/node_modules/lint-staged/node_modules/commander/Readme.md#autotoc_md21614',
        1,
        'Quick Start',
      ],
      [
        '..//Users/vivi/astro/node_modules/postcss-selector-parser/README.md#autotoc_md26214',
        1,
        'Quick Start',
      ],
      [
        '..//Users/vivi/astro/node_modules/swr/README.md#autotoc_md31776',
        1,
        'Quick Start',
      ],
    ],
  ],
  [
    'quick_20start_83',
    [
      'Quick start',
      [
        '..//Users/vivi/astro/node_modules/framer-motion/README.md#autotoc_md15853',
        1,
        '🐇 Quick start',
      ],
      [
        '..//Users/vivi/astro/node_modules/@supabase/auth-js/README.md#autotoc_md6056',
        1,
        'Quick start',
      ],
      [
        '..//Users/vivi/astro/node_modules/@supabase/postgrest-js/README.md#autotoc_md6110',
        1,
        'Quick start',
      ],
    ],
  ],
  [
    'quick_20start_20guide_84',
    [
      'Quick Start Guide',
      [
        '..//Users/vivi/astro/node_modules/@supabase/storage-js/README.md#autotoc_md6129',
        1,
        'Quick Start Guide',
      ],
      [
        '..//Users/vivi/astro/node_modules/rollup/README.md#autotoc_md29639',
        1,
        'Quick Start Guide',
      ],
    ],
  ],
  [
    'quick_20usage_85',
    [
      'Quick usage',
      [
        '..//Users/vivi/astro/node_modules/sucrase/README.md#autotoc_md31696',
        1,
        '',
      ],
    ],
  ],
  [
    'quicklru_20options_86',
    [
      'new QuickLRU(options?)',
      [
        '..//Users/vivi/astro/node_modules/@alloc/quick-lru/readme.md#autotoc_md43',
        1,
        '',
      ],
    ],
  ],
  [
    'quickstart_87',
    [
      'Quickstart',
      [
        '..//Users/vivi/astro/node_modules/fdir/README.md#autotoc_md15300',
        1,
        '🚄 Quickstart',
      ],
      [
        '../md_node__modules_2_0datproto_2api_2_o_a_u_t_h.html',
        1,
        'OAuth Client Quickstart',
      ],
      [
        '..//Users/vivi/astro/node_modules/@vercel/analytics/README.md#autotoc_md7149',
        1,
        'Quickstart',
      ],
      [
        '..//Users/vivi/astro/node_modules/colorette/README.md#autotoc_md10715',
        1,
        'Quickstart',
      ],
      [
        '..//Users/vivi/astro/node_modules/decimal.js-light/README.md#autotoc_md11589',
        1,
        'Quickstart',
      ],
      [
        '..//Users/vivi/astro/node_modules/micromatch/README.md#autotoc_md23916',
        1,
        'Quickstart',
      ],
      [
        '..//Users/vivi/astro/node_modules/react-chartjs-2/README.md#autotoc_md26848',
        1,
        'Quickstart',
      ],
      [
        '..//Users/vivi/astro/node_modules/uuid/README.md#autotoc_md34625',
        1,
        'Quickstart',
      ],
    ],
  ],
  [
    'quill_20icons_88',
    [
      'Quill Icons',
      [
        '../md_node__modules_2_0diconify_2json_2collections.html#autotoc_md3518',
        1,
        '',
      ],
    ],
  ],
  [
    'quit_20tt_89',
    [
      '&lt;tt&gt;.QUIT()&lt;/tt&gt;/&lt;tt&gt;.quit()&lt;/tt&gt;',
      [
        '..//Users/vivi/astro/node_modules/redis/README.md#autotoc_md28087',
        1,
        '',
      ],
    ],
  ],
  [
    'quit_20tt_20tt_20quit_20tt_90',
    [
      '&lt;tt&gt;.QUIT()&lt;/tt&gt;/&lt;tt&gt;.quit()&lt;/tt&gt;',
      [
        '..//Users/vivi/astro/node_modules/redis/README.md#autotoc_md28087',
        1,
        '',
      ],
    ],
  ],
  [
    'quote_91',
    [
      'quote',
      [
        '../md_node__modules_2vite_2_l_i_c_e_n_s_e.html#autotoc_md34994',
        1,
        'commondir, shell-quote',
      ],
      [
        '..//Users/vivi/astro/node_modules/shell-quote/README.md#autotoc_md30647',
        1,
        'quote',
      ],
    ],
  ],
  [
    'quote_20args_92',
    [
      'quote(args)',
      [
        '..//Users/vivi/astro/node_modules/shell-quote/README.md#autotoc_md30654',
        1,
        '',
      ],
    ],
  ],
  [
    'quote_20tt_93',
    [
      '&lt;tt&gt;Quote&lt;/tt&gt;',
      [
        '..//Users/vivi/astro/node_modules/hast-util-to-html/readme.md#autotoc_md17392',
        1,
        '',
      ],
    ],
  ],
  [
    'quote_20tt_94',
    [
      'quote tt',
      [
        '..//Users/vivi/astro/node_modules/mdast-util-to-markdown/readme.md#autotoc_md22800',
        1,
        '&lt;tt&gt;options.quote&lt;/tt&gt;',
      ],
      [
        '..//Users/vivi/astro/node_modules/hast-util-to-html/readme.md#autotoc_md17383',
        1,
        '&lt;tt&gt;quote&lt;/tt&gt;',
      ],
    ],
  ],
  [
    'quotecharactermap_20tt_95',
    [
      '&lt;tt&gt;QuoteCharacterMap&lt;/tt&gt;',
      [
        '..//Users/vivi/astro/node_modules/retext-smartypants/readme.md#autotoc_md29496',
        1,
        '',
      ],
    ],
  ],
  [
    'quoted_20tt_96',
    [
      'quoted tt',
      [
        '../md_node__modules_2eslint-plugin-astro_2node__modules_2postcss-selector-parser_2_a_p_i.html#autotoc_md13073',
        1,
        '&lt;tt&gt;attribute.quoted&lt;/tt&gt;',
      ],
      [
        '../md_node__modules_2postcss-selector-parser_2_a_p_i.html#autotoc_md26139',
        1,
        '&lt;tt&gt;attribute.quoted&lt;/tt&gt;',
      ],
    ],
  ],
  [
    'quotes_97',
    [
      'quotes',
      [
        '../md_node__modules_2_0dtypescript-eslint_2eslint-plugin_2docs_2rules_2quotes.html',
        1,
        'quotes',
      ],
      [
        '../md_tests_2security_2node__modules_2_8pnpm_2_0dtypescript-eslint_09eslint-plugin_0d8_826_81___0dt263720f35887b17eff8e3e7313f87c21.html',
        1,
        'quotes',
      ],
    ],
  ],
  [
    'quotes_20and_20run_20once_20per_20file_98',
    [
      'Example: Wrap filenames in single quotes and run once per file',
      [
        '..//Users/vivi/astro/node_modules/lint-staged/README.md#autotoc_md21826',
        1,
        '',
      ],
    ],
  ],
  [
    'quotes_20tt_99',
    [
      'quotes tt',
      [
        '..//Users/vivi/astro/node_modules/@astrojs/markdown-remark/node_modules/retext-smartypants/readme.md#autotoc_md623',
        1,
        '&lt;tt&gt;options.quotes&lt;/tt&gt;',
      ],
      [
        '..//Users/vivi/astro/node_modules/cssesc/README.md#autotoc_md11178',
        1,
        '&lt;tt&gt;quotes&lt;/tt&gt;',
      ],
      [
        '..//Users/vivi/astro/node_modules/jsesc/README.md#autotoc_md21048',
        1,
        '&lt;tt&gt;quotes&lt;/tt&gt;',
      ],
      [
        '..//Users/vivi/astro/node_modules/regjsparser/node_modules/jsesc/README.md#autotoc_md28673',
        1,
        '&lt;tt&gt;quotes&lt;/tt&gt;',
      ],
    ],
  ],
  [
    'quotes_2emd_100',
    [
      'quotes.md',
      [
        '../node__modules_2_0dtypescript-eslint_2eslint-plugin_2docs_2rules_2quotes_8md.html',
        1,
        '(Global Namespace)',
      ],
      [
        '../tests_2security_2node__modules_2_8pnpm_2_0dtypescript-eslint_09eslint-plugin_0d8_826_81___0dtypea19df7bbe7937fba13becfb94571dbeb.html',
        1,
        '(Global Namespace)',
      ],
    ],
  ],
  [
    'quotesmart_20tt_101',
    [
      '&lt;tt&gt;quoteSmart&lt;/tt&gt;',
      [
        '..//Users/vivi/astro/node_modules/hast-util-to-html/readme.md#autotoc_md17384',
        1,
        '',
      ],
    ],
  ],
]
