var searchData = [
  [
    'natural_20orderby_0',
    [
      'natural-orderby',
      ['../md_node__modules_2natural-orderby_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'next_1',
    [
      'Next',
      [
        '../md_node__modules_2_0djest_2reporters_2node__modules_2_0dbcoe_2v8-coverage_2_c_h_a_n_g_e_l_o_g.html',
        1,
        'Next',
      ],
      [
        '../md_node__modules_2_0djest_2reporters_2node__modules_2_0dbcoe_2v8-coverage_2dist_2lib_2_c_h_a_n_g_e_l_o_g.html',
        1,
        'Next',
      ],
    ],
  ],
  [
    'next_20versions_20change_20notes_20are_20available_20only_20on_20the_20a_20href_20https_3a_20github_20com_20recharts_20recharts_20releases_20github_20releases_20a_20page_20⚠️_2',
    [
      '⚠️ Next versions change notes are available only on the &lt;a href=&quot;https://github.com/recharts/recharts/releases&quot; &gt;GitHub Releases&lt;/a&gt; page ⚠️',
      ['../md_node__modules_2recharts_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'no_20access_20key_3',
    [
      'jsx-a11y/no-access-key',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-access-key.html',
        1,
        '',
      ],
    ],
  ],
  [
    'no_20aria_20hidden_20on_20focusable_4',
    [
      'jsx-a11y/no-aria-hidden-on-focusable',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-aria-hidden-on-focusable.html',
        1,
        '',
      ],
    ],
  ],
  [
    'no_20autofocus_5',
    [
      'jsx-a11y/no-autofocus',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-autofocus.html',
        1,
        '',
      ],
    ],
  ],
  [
    'no_20distracting_20elements_6',
    [
      'jsx-a11y/no-distracting-elements',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-distracting-elements.html',
        1,
        '',
      ],
    ],
  ],
  [
    'no_20extra_20parens_7',
    [
      'no extra parens',
      [
        '../md_node__modules_2_0dtypescript-eslint_2eslint-plugin_2docs_2rules_2no-extra-parens.html',
        1,
        'no-extra-parens',
      ],
      [
        '../md_tests_2security_2node__modules_2_8pnpm_2_0dtypescript-eslint_09eslint-plugin_0d8_826_81___0dt1a170db50858284399151c02b80919b4.html',
        1,
        'no-extra-parens',
      ],
    ],
  ],
  [
    'no_20extra_20semi_8',
    [
      'no extra semi',
      [
        '../md_node__modules_2_0dtypescript-eslint_2eslint-plugin_2docs_2rules_2no-extra-semi.html',
        1,
        'no-extra-semi',
      ],
      [
        '../md_tests_2security_2node__modules_2_8pnpm_2_0dtypescript-eslint_09eslint-plugin_0d8_826_81___0dt38170184672328c1e1d28482a3f2cc15.html',
        1,
        'no-extra-semi',
      ],
    ],
  ],
  [
    'no_20interactive_20element_20to_20noninteractive_20role_9',
    [
      'jsx-a11y/no-interactive-element-to-noninteractive-role',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-interactive-element-to-noninteractive-role.html',
        1,
        '',
      ],
    ],
  ],
  [
    'no_20noninteractive_20element_20interactions_10',
    [
      'jsx-a11y/no-noninteractive-element-interactions',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-noninteractive-element-interactions.html',
        1,
        '',
      ],
    ],
  ],
  [
    'no_20noninteractive_20element_20to_20interactive_20role_11',
    [
      'jsx-a11y/no-noninteractive-element-to-interactive-role',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-noninteractive-element-to-interactive-role.html',
        1,
        '',
      ],
    ],
  ],
  [
    'no_20noninteractive_20tabindex_12',
    [
      'jsx-a11y/no-noninteractive-tabindex',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-noninteractive-tabindex.html',
        1,
        '',
      ],
    ],
  ],
  [
    'no_20onchange_13',
    [
      'jsx-a11y/no-onchange',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-onchange.html',
        1,
        '',
      ],
    ],
  ],
  [
    'no_20positive_14',
    [
      'jsx-a11y/tabindex-no-positive',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2tabindex-no-positive.html',
        1,
        '',
      ],
    ],
  ],
  [
    'no_20redundant_20roles_15',
    [
      'jsx-a11y/no-redundant-roles',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-redundant-roles.html',
        1,
        '',
      ],
    ],
  ],
  [
    'no_20static_20element_20interactions_16',
    [
      'jsx-a11y/no-static-element-interactions',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-static-element-interactions.html',
        1,
        '',
      ],
    ],
  ],
  [
    'node_20license_17',
    [
      'NODE LICENSE',
      [
        '../md_node__modules_2ts-node_2dist-raw_2_n_o_d_e-_l_i_c_e_n_s_e.html',
        1,
        'NODE-LICENSE',
      ],
      [
        '../md_tests_2security_2node__modules_2_8pnpm_2ts-node_0d10_89_82___0dtypes_09node_0d22_813_810__typ15c5fbfe762868366d4943f8c5781f93.html',
        1,
        'NODE-LICENSE',
      ],
    ],
  ],
  [
    'node_20pre_20gyp_20changelog_18',
    [
      'node-pre-gyp changelog',
      [
        '../md_node__modules_2_0dmapbox_2node-pre-gyp_2_c_h_a_n_g_e_l_o_g.html',
        1,
        '',
      ],
    ],
  ],
  [
    'non_20standard_20properties_19',
    [
      'Non-standard properties',
      [
        '../md_node__modules_2fast-equals_2recipes_2non-standard-properties.html',
        1,
        '',
      ],
    ],
  ],
  [
    'noninteractive_20element_20interactions_20',
    [
      'jsx-a11y/no-noninteractive-element-interactions',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-noninteractive-element-interactions.html',
        1,
        '',
      ],
    ],
  ],
  [
    'noninteractive_20element_20to_20interactive_20role_21',
    [
      'jsx-a11y/no-noninteractive-element-to-interactive-role',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-noninteractive-element-to-interactive-role.html',
        1,
        '',
      ],
    ],
  ],
  [
    'noninteractive_20role_22',
    [
      'jsx-a11y/no-interactive-element-to-noninteractive-role',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-interactive-element-to-noninteractive-role.html',
        1,
        '',
      ],
    ],
  ],
  [
    'noninteractive_20tabindex_23',
    [
      'jsx-a11y/no-noninteractive-tabindex',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-noninteractive-tabindex.html',
        1,
        '',
      ],
    ],
  ],
  ['note_24', ['Note', ['../md_node__modules_2chai_2_history.html', 1, '']]],
  [
    'notes_25',
    [
      'Notes',
      [
        '../md_node__modules_2_0dflydotio_2dockerfile_2node__modules_2diff_2release-notes.html',
        1,
        'Release Notes',
      ],
      ['../md_node__modules_2chai_2_release_notes.html', 1, 'Release Notes'],
      ['../md_node__modules_2diff_2release-notes.html', 1, 'Release Notes'],
      [
        '../md_node__modules_2ts-node_2node__modules_2diff_2release-notes.html',
        1,
        'Release Notes',
      ],
    ],
  ],
  [
    'notes_20are_20available_20only_20on_20the_20a_20href_20https_3a_20github_20com_20recharts_20recharts_20releases_20github_20releases_20a_20page_20⚠️_26',
    [
      '⚠️ Next versions change notes are available only on the &lt;a href=&quot;https://github.com/recharts/recharts/releases&quot; &gt;GitHub Releases&lt;/a&gt; page ⚠️',
      ['../md_node__modules_2recharts_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'notification_20service_20api_20documentation_27',
    [
      'Notification Service API Documentation',
      ['../md_src_2docs_2api_2notification-service.html', 1, ''],
    ],
  ],
  [
    'npmjs_20org_20package_20object_20inspect_20img_20src_20https_3a_20versionbadg_20es_20inspect_20js_20object_20inspect_20svg_20alt_20version_20badge_20a_20sup_28',
    [
      'object-inspect &lt;sup&gt;&lt;a href=&quot;https://npmjs.org/package/object-inspect&quot; &gt;&lt;img src=&quot;https://versionbadg.es/inspect-js/object-inspect.svg&quot; alt=&quot;Version Badge&quot;/&gt;&lt;/a&gt;&lt;/sup&gt;',
      ['../md_node__modules_2object-inspect_2readme.html', 1, ''],
    ],
  ],
  [
    'npmjs_20org_20package_20resolve_20img_20src_20https_3a_20versionbadg_20es_20browserify_20resolve_20svg_20alt_20version_20badge_20a_20sup_29',
    [
      'npmjs org package resolve img src https: versionbadg es browserify resolve svg alt Version Badge a sup',
      [
        '../md_node__modules_2eslint-plugin-react_2node__modules_2resolve_2readme.html',
        1,
        'resolve &lt;sup&gt;&lt;a href=&quot;https://npmjs.org/package/resolve&quot; &gt;&lt;img src=&quot;https://versionbadg.es/browserify/resolve.svg&quot; alt=&quot;Version Badge&quot;/&gt;&lt;/a&gt;&lt;/sup&gt;',
      ],
      [
        '../md_node__modules_2resolve_2readme.html',
        1,
        'resolve &lt;sup&gt;&lt;a href=&quot;https://npmjs.org/package/resolve&quot; &gt;&lt;img src=&quot;https://versionbadg.es/browserify/resolve.svg&quot; alt=&quot;Version Badge&quot;/&gt;&lt;/a&gt;&lt;/sup&gt;',
      ],
    ],
  ],
  [
    'nprogress_20compare_20v0_201_206_20v0_202_200_20v0_202_200_20a_20may_2013_202015_30',
    [
      '&lt;a href=&quot;https://github.com/rstacruz/nprogress/compare/v0.1.6...v0.2.0&quot; &gt;v0.2.0&lt;/a&gt; - May 13, 2015',
      ['../md_node__modules_2nprogress_2_history.html', 1, ''],
    ],
  ],
]
