var searchData = [
  [
    'a_0',
    [
      'a',
      [
        '../md_node__modules_2deepmerge_2changelog.html',
        1,
        '&lt;a href=&quot;https://github.com/TehShrike/deepmerge/releases/tag/v4.3.1&quot; &gt;4.3.1&lt;/a&gt;',
      ],
      [
        '../md_node__modules_2universal-user-agent_2_l_i_c_e_n_s_e.html',
        1,
        '&lt;a href=&quot;https://spdx.org/licenses/ISC&quot; &gt;ISC License&lt;/a&gt;',
      ],
    ],
  ],
  [
    'a_202021_2003_2006_1',
    [
      'a 2021 03 06',
      [
        '../md_node__modules_2chokidar_2node__modules_2glob-parent_2_c_h_a_n_g_e_l_o_g.html',
        1,
        '&lt;a href=&quot;https://github.com/gulpjs/glob-parent/compare/v5.1.1...v5.1.2&quot; &gt;5.1.2&lt;/a&gt; (2021-03-06)',
      ],
      [
        '../md_node__modules_2fast-glob_2node__modules_2glob-parent_2_c_h_a_n_g_e_l_o_g.html',
        1,
        '&lt;a href=&quot;https://github.com/gulpjs/glob-parent/compare/v5.1.1...v5.1.2&quot; &gt;5.1.2&lt;/a&gt; (2021-03-06)',
      ],
    ],
  ],
  [
    'a_202022_2010_2018_2',
    [
      '&lt;a href=&quot;https://github.com/rvagg/bl/compare/v5.0.0...v5.1.0&quot; &gt;5.1.0&lt;/a&gt; (2022-10-18)',
      ['../md_node__modules_2bl_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'a_202023_2007_2005_3',
    [
      '&lt;a href=&quot;https://github.com/SimenB/collect-v8-coverage/compare/v1.0.1...v1.0.2&quot; &gt;1.0.2&lt;/a&gt; (2023-07-05)',
      [
        '../md_node__modules_2collect-v8-coverage_2_c_h_a_n_g_e_l_o_g.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a_202023_2009_2019_4',
    [
      '&lt;a href=&quot;https://github.com/iamkun/dayjs/compare/v1.11.9...v1.11.10&quot; &gt;1.11.10&lt;/a&gt; (2023-09-19)',
      ['../md_node__modules_2dayjs_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'a_202023_2011_2016_5',
    [
      '&lt;a href=&quot;https://github.com/francoischalifour/medium-zoom/compare/1.0.8...1.1.0&quot; &gt;1.1.0&lt;/a&gt; (2023-11-16)',
      ['../md_node__modules_2medium-zoom_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'a_202025_2002_2022_6',
    [
      '&lt;a href=&quot;https://github.com/reactivex/rxjs/compare/7.8.1...7.8.2&quot; &gt;7.8.2&lt;/a&gt; (2025-02-22)',
      ['../md_node__modules_2rxjs_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'a_202025_2003_2021_7',
    [
      '&lt;a href=&quot;https://github.com/kulshekhar/ts-jest/compare/v29.2.6...v29.3.0&quot; &gt;29.3.0&lt;/a&gt; (2025-03-21)',
      ['../md_node__modules_2ts-jest_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'a_20build_8',
    [
      'Reproducing a build',
      ['../md_node__modules_2fast-equals_2_b_u_i_l_d.html', 1, ''],
    ],
  ],
  [
    'a_20href_20https_3a_20github_20com_20francoischalifour_20medium_20zoom_20compare_201_200_208_201_201_200_201_201_200_20a_202023_2011_2016_9',
    [
      '&lt;a href=&quot;https://github.com/francoischalifour/medium-zoom/compare/1.0.8...1.1.0&quot; &gt;1.1.0&lt;/a&gt; (2023-11-16)',
      ['../md_node__modules_2medium-zoom_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'a_20href_20https_3a_20github_20com_20gulpjs_20glob_20parent_20compare_20v5_201_201_20v5_201_202_205_201_202_20a_202021_2003_2006_10',
    [
      'a href https: github com gulpjs glob parent compare v5 1 1 v5 1 2 5 1 2 a 2021 03 06',
      [
        '../md_node__modules_2chokidar_2node__modules_2glob-parent_2_c_h_a_n_g_e_l_o_g.html',
        1,
        '&lt;a href=&quot;https://github.com/gulpjs/glob-parent/compare/v5.1.1...v5.1.2&quot; &gt;5.1.2&lt;/a&gt; (2021-03-06)',
      ],
      [
        '../md_node__modules_2fast-glob_2node__modules_2glob-parent_2_c_h_a_n_g_e_l_o_g.html',
        1,
        '&lt;a href=&quot;https://github.com/gulpjs/glob-parent/compare/v5.1.1...v5.1.2&quot; &gt;5.1.2&lt;/a&gt; (2021-03-06)',
      ],
    ],
  ],
  [
    'a_20href_20https_3a_20github_20com_20iamkun_20dayjs_20compare_20v1_2011_209_20v1_2011_2010_201_2011_2010_20a_202023_2009_2019_11',
    [
      '&lt;a href=&quot;https://github.com/iamkun/dayjs/compare/v1.11.9...v1.11.10&quot; &gt;1.11.10&lt;/a&gt; (2023-09-19)',
      ['../md_node__modules_2dayjs_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'a_20href_20https_3a_20github_20com_20kulshekhar_20ts_20jest_20compare_20v29_202_206_20v29_203_200_2029_203_200_20a_202025_2003_2021_12',
    [
      '&lt;a href=&quot;https://github.com/kulshekhar/ts-jest/compare/v29.2.6...v29.3.0&quot; &gt;29.3.0&lt;/a&gt; (2025-03-21)',
      ['../md_node__modules_2ts-jest_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'a_20href_20https_3a_20github_20com_20reactivex_20rxjs_20compare_207_208_201_207_208_202_207_208_202_20a_202025_2002_2022_13',
    [
      '&lt;a href=&quot;https://github.com/reactivex/rxjs/compare/7.8.1...7.8.2&quot; &gt;7.8.2&lt;/a&gt; (2025-02-22)',
      ['../md_node__modules_2rxjs_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'a_20href_20https_3a_20github_20com_20recharts_20recharts_20releases_20github_20releases_20a_20page_20⚠️_14',
    [
      '⚠️ Next versions change notes are available only on the &lt;a href=&quot;https://github.com/recharts/recharts/releases&quot; &gt;GitHub Releases&lt;/a&gt; page ⚠️',
      ['../md_node__modules_2recharts_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'a_20href_20https_3a_20github_20com_20rstacruz_20nprogress_20compare_20v0_201_206_20v0_202_200_20v0_202_200_20a_20may_2013_202015_15',
    [
      '&lt;a href=&quot;https://github.com/rstacruz/nprogress/compare/v0.1.6...v0.2.0&quot; &gt;v0.2.0&lt;/a&gt; - May 13, 2015',
      ['../md_node__modules_2nprogress_2_history.html', 1, ''],
    ],
  ],
  [
    'a_20href_20https_3a_20github_20com_20rvagg_20bl_20compare_20v5_200_200_20v5_201_200_205_201_200_20a_202022_2010_2018_16',
    [
      '&lt;a href=&quot;https://github.com/rvagg/bl/compare/v5.0.0...v5.1.0&quot; &gt;5.1.0&lt;/a&gt; (2022-10-18)',
      ['../md_node__modules_2bl_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'a_20href_20https_3a_20github_20com_20simenb_20collect_20v8_20coverage_20compare_20v1_200_201_20v1_200_202_201_200_202_20a_202023_2007_2005_17',
    [
      '&lt;a href=&quot;https://github.com/SimenB/collect-v8-coverage/compare/v1.0.1...v1.0.2&quot; &gt;1.0.2&lt;/a&gt; (2023-07-05)',
      [
        '../md_node__modules_2collect-v8-coverage_2_c_h_a_n_g_e_l_o_g.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a_20href_20https_3a_20github_20com_20tehshrike_20deepmerge_20releases_20tag_20v4_203_201_204_203_201_20a_18',
    [
      '&lt;a href=&quot;https://github.com/TehShrike/deepmerge/releases/tag/v4.3.1&quot; &gt;4.3.1&lt;/a&gt;',
      ['../md_node__modules_2deepmerge_2changelog.html', 1, ''],
    ],
  ],
  [
    'a_20href_20https_3a_20npmjs_20org_20package_20object_20inspect_20img_20src_20https_3a_20versionbadg_20es_20inspect_20js_20object_20inspect_20svg_20alt_20version_20badge_20a_20sup_19',
    [
      'object-inspect &lt;sup&gt;&lt;a href=&quot;https://npmjs.org/package/object-inspect&quot; &gt;&lt;img src=&quot;https://versionbadg.es/inspect-js/object-inspect.svg&quot; alt=&quot;Version Badge&quot;/&gt;&lt;/a&gt;&lt;/sup&gt;',
      ['../md_node__modules_2object-inspect_2readme.html', 1, ''],
    ],
  ],
  [
    'a_20href_20https_3a_20npmjs_20org_20package_20resolve_20img_20src_20https_3a_20versionbadg_20es_20browserify_20resolve_20svg_20alt_20version_20badge_20a_20sup_20',
    [
      'a href https: npmjs org package resolve img src https: versionbadg es browserify resolve svg alt Version Badge a sup',
      [
        '../md_node__modules_2eslint-plugin-react_2node__modules_2resolve_2readme.html',
        1,
        'resolve &lt;sup&gt;&lt;a href=&quot;https://npmjs.org/package/resolve&quot; &gt;&lt;img src=&quot;https://versionbadg.es/browserify/resolve.svg&quot; alt=&quot;Version Badge&quot;/&gt;&lt;/a&gt;&lt;/sup&gt;',
      ],
      [
        '../md_node__modules_2resolve_2readme.html',
        1,
        'resolve &lt;sup&gt;&lt;a href=&quot;https://npmjs.org/package/resolve&quot; &gt;&lt;img src=&quot;https://versionbadg.es/browserify/resolve.svg&quot; alt=&quot;Version Badge&quot;/&gt;&lt;/a&gt;&lt;/sup&gt;',
      ],
    ],
  ],
  [
    'a_20href_20https_3a_20spdx_20org_20licenses_20isc_20isc_20license_20a_21',
    [
      '&lt;a href=&quot;https://spdx.org/licenses/ISC&quot; &gt;ISC License&lt;/a&gt;',
      ['../md_node__modules_2universal-user-agent_2_l_i_c_e_n_s_e.html', 1, ''],
    ],
  ],
  [
    'a_20may_2013_202015_22',
    [
      '&lt;a href=&quot;https://github.com/rstacruz/nprogress/compare/v0.1.6...v0.2.0&quot; &gt;v0.2.0&lt;/a&gt; - May 13, 2015',
      ['../md_node__modules_2nprogress_2_history.html', 1, ''],
    ],
  ],
  [
    'a_20page_20⚠️_23',
    [
      '⚠️ Next versions change notes are available only on the &lt;a href=&quot;https://github.com/recharts/recharts/releases&quot; &gt;GitHub Releases&lt;/a&gt; page ⚠️',
      ['../md_node__modules_2recharts_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'a_20release_24',
    [
      'Instructions for making a release',
      [
        '../md_node__modules_2_0dmapbox_2node-pre-gyp_2_r_e_l_e_a_s_e.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a_20sup_25',
    [
      'a sup',
      [
        '../md_node__modules_2object-inspect_2readme.html',
        1,
        'object-inspect &lt;sup&gt;&lt;a href=&quot;https://npmjs.org/package/object-inspect&quot; &gt;&lt;img src=&quot;https://versionbadg.es/inspect-js/object-inspect.svg&quot; alt=&quot;Version Badge&quot;/&gt;&lt;/a&gt;&lt;/sup&gt;',
      ],
      [
        '../md_node__modules_2eslint-plugin-react_2node__modules_2resolve_2readme.html',
        1,
        'resolve &lt;sup&gt;&lt;a href=&quot;https://npmjs.org/package/resolve&quot; &gt;&lt;img src=&quot;https://versionbadg.es/browserify/resolve.svg&quot; alt=&quot;Version Badge&quot;/&gt;&lt;/a&gt;&lt;/sup&gt;',
      ],
      [
        '../md_node__modules_2resolve_2readme.html',
        1,
        'resolve &lt;sup&gt;&lt;a href=&quot;https://npmjs.org/package/resolve&quot; &gt;&lt;img src=&quot;https://versionbadg.es/browserify/resolve.svg&quot; alt=&quot;Version Badge&quot;/&gt;&lt;/a&gt;&lt;/sup&gt;',
      ],
    ],
  ],
  [
    'a_20websocket_20proxy_20in_20front_20of_20your_20own_20postgres_20instance_26',
    [
      'Deploying a WebSocket proxy in front of your own Postgres instance',
      [
        '../md_node__modules_2_0dneondatabase_2serverless_2_d_e_p_l_o_y.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20accessible_20emoji_27',
    [
      'jsx-a11y/accessible-emoji',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2accessible-emoji.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20alt_20text_28',
    [
      'jsx-a11y/alt-text',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2alt-text.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20anchor_20ambiguous_20text_29',
    [
      'jsx-a11y/anchor-ambiguous-text',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2anchor-ambiguous-text.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20anchor_20has_20content_30',
    [
      'jsx-a11y/anchor-has-content',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2anchor-has-content.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20anchor_20is_20valid_31',
    [
      'jsx-a11y/anchor-is-valid',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2anchor-is-valid.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20aria_20activedescendant_20has_20tabindex_32',
    [
      'jsx-a11y/aria-activedescendant-has-tabindex',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2aria-activedescendant-has-tabindex.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20aria_20props_33',
    [
      'jsx-a11y/aria-props',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2aria-props.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20aria_20proptypes_34',
    [
      'jsx-a11y/aria-proptypes',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2aria-proptypes.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20aria_20role_35',
    [
      'jsx-a11y/aria-role',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2aria-role.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20aria_20unsupported_20elements_36',
    [
      'jsx-a11y/aria-unsupported-elements',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2aria-unsupported-elements.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20autocomplete_20valid_37',
    [
      'jsx-a11y/autocomplete-valid',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2autocomplete-valid.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20click_20events_20have_20key_20events_38',
    [
      'jsx-a11y/click-events-have-key-events',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2click-events-have-key-events.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20control_20has_20associated_20label_39',
    [
      'jsx-a11y/control-has-associated-label',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2control-has-associated-label.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20heading_20has_20content_40',
    [
      'jsx-a11y/heading-has-content',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2heading-has-content.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20html_20has_20lang_41',
    [
      'jsx-a11y/html-has-lang',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2html-has-lang.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20iframe_20has_20title_42',
    [
      'jsx-a11y/iframe-has-title',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2iframe-has-title.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20img_20redundant_20alt_43',
    [
      'jsx-a11y/img-redundant-alt',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2img-redundant-alt.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20interactive_20supports_20focus_44',
    [
      'jsx-a11y/interactive-supports-focus',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2interactive-supports-focus.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20label_20has_20associated_20control_45',
    [
      'jsx-a11y/label-has-associated-control',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2label-has-associated-control.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20label_20has_20for_46',
    [
      'jsx-a11y/label-has-for',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2label-has-for.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20lang_47',
    [
      'jsx-a11y/lang',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2lang.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20media_20has_20caption_48',
    [
      'jsx-a11y/media-has-caption',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2media-has-caption.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20mouse_20events_20have_20key_20events_49',
    [
      'jsx-a11y/mouse-events-have-key-events',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2mouse-events-have-key-events.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20no_20access_20key_50',
    [
      'jsx-a11y/no-access-key',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-access-key.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20no_20aria_20hidden_20on_20focusable_51',
    [
      'jsx-a11y/no-aria-hidden-on-focusable',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-aria-hidden-on-focusable.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20no_20autofocus_52',
    [
      'jsx-a11y/no-autofocus',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-autofocus.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20no_20distracting_20elements_53',
    [
      'jsx-a11y/no-distracting-elements',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-distracting-elements.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20no_20interactive_20element_20to_20noninteractive_20role_54',
    [
      'jsx-a11y/no-interactive-element-to-noninteractive-role',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-interactive-element-to-noninteractive-role.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20no_20noninteractive_20element_20interactions_55',
    [
      'jsx-a11y/no-noninteractive-element-interactions',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-noninteractive-element-interactions.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20no_20noninteractive_20element_20to_20interactive_20role_56',
    [
      'jsx-a11y/no-noninteractive-element-to-interactive-role',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-noninteractive-element-to-interactive-role.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20no_20noninteractive_20tabindex_57',
    [
      'jsx-a11y/no-noninteractive-tabindex',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-noninteractive-tabindex.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20no_20onchange_58',
    [
      'jsx-a11y/no-onchange',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-onchange.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20no_20redundant_20roles_59',
    [
      'jsx-a11y/no-redundant-roles',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-redundant-roles.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20no_20static_20element_20interactions_60',
    [
      'jsx-a11y/no-static-element-interactions',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-static-element-interactions.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20prefer_20tag_20over_20role_61',
    [
      'jsx-a11y/prefer-tag-over-role',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2prefer-tag-over-role.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20role_20has_20required_20aria_20props_62',
    [
      'jsx-a11y/role-has-required-aria-props',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2role-has-required-aria-props.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20role_20supports_20aria_20props_63',
    [
      'jsx-a11y/role-supports-aria-props',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2role-supports-aria-props.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20scope_64',
    [
      'jsx-a11y/scope',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2scope.html',
        1,
        '',
      ],
    ],
  ],
  [
    'a11y_20tabindex_20no_20positive_65',
    [
      'jsx-a11y/tabindex-no-positive',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2tabindex-no-positive.html',
        1,
        '',
      ],
    ],
  ],
  [
    'access_66',
    [
      'State access',
      ['../md_node__modules_2moo-color_2docs_2state-access.html', 1, ''],
    ],
  ],
  [
    'access_20key_67',
    [
      'jsx-a11y/no-access-key',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-access-key.html',
        1,
        '',
      ],
    ],
  ],
  [
    'accessible_20emoji_68',
    [
      'jsx-a11y/accessible-emoji',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2accessible-emoji.html',
        1,
        '',
      ],
    ],
  ],
  [
    'activedescendant_20has_20tabindex_69',
    [
      'jsx-a11y/aria-activedescendant-has-tabindex',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2aria-activedescendant-has-tabindex.html',
        1,
        '',
      ],
    ],
  ],
  [
    'adr_200000_20adr_20template_70',
    [
      '[ADR-0000] ADR Template',
      [
        '../md_src_2docs_2architecture_2decisions_20000-adr-template.html',
        1,
        '',
      ],
    ],
  ],
  [
    'adr_200001_20core_20architecture_20decisions_71',
    [
      '[ADR-0001] Core Architecture Decisions',
      [
        '../md_src_2docs_2architecture_2decisions_20001-core-architecture.html',
        1,
        '',
      ],
    ],
  ],
  [
    'adr_20template_72',
    [
      '[ADR-0000] ADR Template',
      [
        '../md_src_2docs_2architecture_2decisions_20000-adr-template.html',
        1,
        '',
      ],
    ],
  ],
  [
    'ai_20components_73',
    [
      'HIPAA Compliance Verification Checklist for AI Components',
      ['../md_src_2docs_2compliance_2hipaa-ai-verification.html', 1, ''],
    ],
  ],
  [
    'ai_20components_20penetration_20testing_20plan_74',
    [
      'AI Components Penetration Testing Plan',
      ['../md_src_2docs_2security_2ai-penetration-testing-plan.html', 1, ''],
    ],
  ],
  [
    'ai_20mental_20health_20assistance_75',
    [
      'ai-mental-health-assistance',
      ['../md_src_2content_2blog_2ai-mental-health-assistance.html', 1, ''],
    ],
  ],
  [
    'ai_20world_76',
    [
      'emotional-intelligence-in-ai-world',
      [
        '../md_src_2content_2blog_2emotional-intelligence-in-ai-world.html',
        1,
        '',
      ],
    ],
  ],
  [
    'algorithms_77',
    [
      'Changes to CSS Parser Algorithms',
      [
        '../md_node__modules_2_0dcsstools_2css-parser-algorithms_2_c_h_a_n_g_e_l_o_g.html',
        1,
        '',
      ],
    ],
  ],
  [
    'alloc_20api_78',
    [
      'Porting to the Buffer.from/Buffer.alloc API',
      ['../md_node__modules_2safer-buffer_2_porting-_buffer.html', 1, ''],
    ],
  ],
  [
    'alt_79',
    [
      'jsx-a11y/img-redundant-alt',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2img-redundant-alt.html',
        1,
        '',
      ],
    ],
  ],
  [
    'alt_20text_80',
    [
      'jsx-a11y/alt-text',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2alt-text.html',
        1,
        '',
      ],
    ],
  ],
  [
    'alt_20version_20badge_20a_20sup_81',
    [
      'alt Version Badge a sup',
      [
        '../md_node__modules_2object-inspect_2readme.html',
        1,
        'object-inspect &lt;sup&gt;&lt;a href=&quot;https://npmjs.org/package/object-inspect&quot; &gt;&lt;img src=&quot;https://versionbadg.es/inspect-js/object-inspect.svg&quot; alt=&quot;Version Badge&quot;/&gt;&lt;/a&gt;&lt;/sup&gt;',
      ],
      [
        '../md_node__modules_2eslint-plugin-react_2node__modules_2resolve_2readme.html',
        1,
        'resolve &lt;sup&gt;&lt;a href=&quot;https://npmjs.org/package/resolve&quot; &gt;&lt;img src=&quot;https://versionbadg.es/browserify/resolve.svg&quot; alt=&quot;Version Badge&quot;/&gt;&lt;/a&gt;&lt;/sup&gt;',
      ],
      [
        '../md_node__modules_2resolve_2readme.html',
        1,
        'resolve &lt;sup&gt;&lt;a href=&quot;https://npmjs.org/package/resolve&quot; &gt;&lt;img src=&quot;https://versionbadg.es/browserify/resolve.svg&quot; alt=&quot;Version Badge&quot;/&gt;&lt;/a&gt;&lt;/sup&gt;',
      ],
    ],
  ],
  [
    'ambiguous_20text_82',
    [
      'jsx-a11y/anchor-ambiguous-text',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2anchor-ambiguous-text.html',
        1,
        '',
      ],
    ],
  ],
  [
    'analytics_20integration_83',
    [
      'Litlyx Analytics Integration',
      ['../md_src_2docs_2analytics_2litlyx-integration.html', 1, ''],
    ],
  ],
  [
    'anchor_20ambiguous_20text_84',
    [
      'jsx-a11y/anchor-ambiguous-text',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2anchor-ambiguous-text.html',
        1,
        '',
      ],
    ],
  ],
  [
    'anchor_20has_20content_85',
    [
      'jsx-a11y/anchor-has-content',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2anchor-has-content.html',
        1,
        '',
      ],
    ],
  ],
  [
    'anchor_20is_20valid_86',
    [
      'jsx-a11y/anchor-is-valid',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2anchor-is-valid.html',
        1,
        '',
      ],
    ],
  ],
  [
    'and_20configuration_87',
    [
      'Options and configuration',
      [
        '../md_node__modules_2_0dneondatabase_2serverless_2_c_o_n_f_i_g.html',
        1,
        '',
      ],
    ],
  ],
  [
    'and_20contributing_88',
    [
      'Development and contributing',
      [
        '../md_node__modules_2_0dneondatabase_2serverless_2_d_e_v_e_l_o_p.html',
        1,
        '',
      ],
    ],
  ],
  [
    'and_20logging_89',
    [
      'Security Monitoring and Logging',
      ['../md_src_2docs_2security_2monitoring.html', 1, ''],
    ],
  ],
  [
    'annotation_20spacing_90',
    [
      'annotation spacing',
      [
        '../md_node__modules_2_0dtypescript-eslint_2eslint-plugin_2docs_2rules_2type-annotation-spacing.html',
        1,
        'type-annotation-spacing',
      ],
      [
        '../md_tests_2security_2node__modules_2_8pnpm_2_0dtypescript-eslint_09eslint-plugin_0d8_826_81___0dt5c7011f4fd0fc9c3bb45ed95bc9ea34b.html',
        1,
        'type-annotation-spacing',
      ],
    ],
  ],
  [
    'api_91',
    [
      'API',
      ['../md_node__modules_2sitemap_2api.html', 1, 'API'],
      [
        '../md_node__modules_2_0datproto_2api_2docs_2moderation.html',
        1,
        'Moderation API',
      ],
      [
        '../md_node__modules_2safer-buffer_2_porting-_buffer.html',
        1,
        'Porting to the Buffer.from/Buffer.alloc API',
      ],
    ],
  ],
  [
    'api_92',
    [
      '@atproto/api',
      ['../md_node__modules_2_0datproto_2api_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'api_20documentation_93',
    [
      'API Documentation',
      [
        '../md_node__modules_2eslint-plugin-astro_2node__modules_2postcss-selector-parser_2_a_p_i.html',
        1,
        'API Documentation',
      ],
      [
        '../md_node__modules_2postcss-selector-parser_2_a_p_i.html',
        1,
        'API Documentation',
      ],
      [
        '../md_src_2docs_2api_2notification-service.html',
        1,
        'Notification Service API Documentation',
      ],
    ],
  ],
  [
    'api_20reference_94',
    [
      'Plugin API Reference',
      ['../md_src_2docs_2api_2plugins_2api.html', 1, ''],
    ],
  ],
  [
    'architecture_20decisions_95',
    [
      '[ADR-0001] Core Architecture Decisions',
      [
        '../md_src_2docs_2architecture_2decisions_20001-core-architecture.html',
        1,
        '',
      ],
    ],
  ],
  [
    'are_20available_20only_20on_20the_20a_20href_20https_3a_20github_20com_20recharts_20recharts_20releases_20github_20releases_20a_20page_20⚠️_96',
    [
      '⚠️ Next versions change notes are available only on the &lt;a href=&quot;https://github.com/recharts/recharts/releases&quot; &gt;GitHub Releases&lt;/a&gt; page ⚠️',
      ['../md_node__modules_2recharts_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'aria_20activedescendant_20has_20tabindex_97',
    [
      'jsx-a11y/aria-activedescendant-has-tabindex',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2aria-activedescendant-has-tabindex.html',
        1,
        '',
      ],
    ],
  ],
  [
    'aria_20hidden_20on_20focusable_98',
    [
      'jsx-a11y/no-aria-hidden-on-focusable',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-aria-hidden-on-focusable.html',
        1,
        '',
      ],
    ],
  ],
  [
    'aria_20props_99',
    [
      'aria props',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2aria-props.html',
        1,
        'jsx-a11y/aria-props',
      ],
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2role-has-required-aria-props.html',
        1,
        'jsx-a11y/role-has-required-aria-props',
      ],
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2role-supports-aria-props.html',
        1,
        'jsx-a11y/role-supports-aria-props',
      ],
    ],
  ],
  [
    'aria_20proptypes_100',
    [
      'jsx-a11y/aria-proptypes',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2aria-proptypes.html',
        1,
        '',
      ],
    ],
  ],
  [
    'aria_20query_20change_20log_101',
    [
      'aria-query Change Log',
      [
        '../md_node__modules_2_0dtesting-library_2dom_2node__modules_2aria-query_2_c_h_a_n_g_e_l_o_g.html',
        1,
        '',
      ],
    ],
  ],
  [
    'aria_20role_102',
    [
      'jsx-a11y/aria-role',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2aria-role.html',
        1,
        '',
      ],
    ],
  ],
  [
    'aria_20unsupported_20elements_103',
    [
      'jsx-a11y/aria-unsupported-elements',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2aria-unsupported-elements.html',
        1,
        '',
      ],
    ],
  ],
  [
    'around_20comment_104',
    [
      'around comment',
      [
        '../md_node__modules_2_0dtypescript-eslint_2eslint-plugin_2docs_2rules_2lines-around-comment.html',
        1,
        'lines-around-comment',
      ],
      [
        '../md_tests_2security_2node__modules_2_8pnpm_2_0dtypescript-eslint_09eslint-plugin_0d8_826_81___0dt61d87509504139c2ffc539f4d159c240.html',
        1,
        'lines-around-comment',
      ],
    ],
  ],
  ['ascent_105', ['Gradiant Ascent', ['../md__r_e_a_d_m_e.html', 1, '']]],
  [
    'assistance_106',
    [
      'ai-mental-health-assistance',
      ['../md_src_2content_2blog_2ai-mental-health-assistance.html', 1, ''],
    ],
  ],
  [
    'associated_20control_107',
    [
      'jsx-a11y/label-has-associated-control',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2label-has-associated-control.html',
        1,
        '',
      ],
    ],
  ],
  [
    'associated_20label_108',
    [
      'jsx-a11y/control-has-associated-label',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2control-has-associated-label.html',
        1,
        '',
      ],
    ],
  ],
  [
    'astrojs_20starlight_109',
    [
      '@astrojs/starlight',
      [
        '../md_node__modules_2_0dastrojs_2starlight_2_c_h_a_n_g_e_l_o_g.html',
        1,
        '',
      ],
    ],
  ],
  [
    'atproto_20api_110',
    [
      '@atproto/api',
      ['../md_node__modules_2_0datproto_2api_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'atproto_20common_20web_111',
    [
      '@atproto/common-web',
      [
        '../md_node__modules_2_0datproto_2common-web_2_c_h_a_n_g_e_l_o_g.html',
        1,
        '',
      ],
    ],
  ],
  [
    'atproto_20lexicon_112',
    [
      '@atproto/lexicon',
      [
        '../md_node__modules_2_0datproto_2lexicon_2_c_h_a_n_g_e_l_o_g.html',
        1,
        '',
      ],
    ],
  ],
  [
    'atproto_20syntax_113',
    [
      '@atproto/syntax',
      [
        '../md_node__modules_2_0datproto_2syntax_2_c_h_a_n_g_e_l_o_g.html',
        1,
        '',
      ],
    ],
  ],
  [
    'atproto_20xrpc_114',
    [
      '@atproto/xrpc',
      ['../md_node__modules_2_0datproto_2xrpc_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'authors_115',
    ['Authors', ['../md_node__modules_2buffer_2_a_u_t_h_o_r_s.html', 1, '']],
  ],
  [
    'autocomplete_20valid_116',
    [
      'jsx-a11y/autocomplete-valid',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2autocomplete-valid.html',
        1,
        '',
      ],
    ],
  ],
  [
    'autofocus_117',
    [
      'jsx-a11y/no-autofocus',
      [
        '../md_node__modules_2eslint-plugin-jsx-a11y_2docs_2rules_2no-autofocus.html',
        1,
        '',
      ],
    ],
  ],
  [
    'available_20only_20on_20the_20a_20href_20https_3a_20github_20com_20recharts_20recharts_20releases_20github_20releases_20a_20page_20⚠️_118',
    [
      '⚠️ Next versions change notes are available only on the &lt;a href=&quot;https://github.com/recharts/recharts/releases&quot; &gt;GitHub Releases&lt;/a&gt; page ⚠️',
      ['../md_node__modules_2recharts_2_c_h_a_n_g_e_l_o_g.html', 1, ''],
    ],
  ],
  [
    'available_20tt_20language_20tt_20imports_119',
    [
      'Available tt language tt imports',
      [
        '../md_node__modules_2react-syntax-highlighter_2_a_v_a_i_l_a_b_l_e___l_a_n_g_u_a_g_e_s___h_l_j_s.html',
        1,
        'Available &lt;tt&gt;language&lt;/tt&gt; imports',
      ],
      [
        '../md_node__modules_2react-syntax-highlighter_2_a_v_a_i_l_a_b_l_e___l_a_n_g_u_a_g_e_s___p_r_i_s_m.html',
        1,
        'Available &lt;tt&gt;language&lt;/tt&gt; imports',
      ],
    ],
  ],
  [
    'available_20tt_20stylesheet_20tt_20props_120',
    [
      'Available tt stylesheet tt props',
      [
        '../md_node__modules_2react-syntax-highlighter_2_a_v_a_i_l_a_b_l_e___s_t_y_l_e_s___h_l_j_s.html',
        1,
        'Available &lt;tt&gt;stylesheet&lt;/tt&gt; props',
      ],
      [
        '../md_node__modules_2react-syntax-highlighter_2_a_v_a_i_l_a_b_l_e___s_t_y_l_e_s___p_r_i_s_m.html',
        1,
        'Available &lt;tt&gt;stylesheet&lt;/tt&gt; props',
      ],
    ],
  ],
]
