# Gitleaks configuration for healthcare data
title = "Gitleaks Healthcare Configuration"

[allowlist]
description = "Global allow list"
paths = [
    '''.*\.test\.ts$''',
    '''.*\.test\.tsx$''',
    '''.*\.spec\.ts$''',
    '''.*\.spec\.tsx$''',
    '''.*test/.*''',
    '''.*tests/.*''',
    '''.*/__tests__/.*''',
    '''.*/__mocks__/.*''',
    '''.*\.md$''',
    '''package-lock\.json$''',
    '''yarn\.lock$''',
]

# Standard secret detection rules
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|apikey|api_key_secret)([^a-zA-Z0-9]|$){0,1}[=:"\s'\``]{1,2}([a-zA-Z0-9=_\-\+/]{16,45})'''
secretGroup = 3
entropy = 3.7

[[rules]]
id = "generic-secret"
description = "Generic Secret"
regex = '''(?i)(secret|password|credentials)([^a-zA-Z0-9]|$){0,1}[=:"\s'\``]{1,2}([a-zA-Z0-9=_\-\+/]{16,45})'''
secretGroup = 3
entropy = 3.7

# Healthcare-specific rules
[[rules]]
id = "ehr-api-key"
description = "EHR API Key"
regex = '''(?i)(epic|cerner|allscripts|athena)([_-]?api[_-]?key|apikey)([^a-zA-Z0-9]|$){0,1}[=:"\s'\``]{1,2}([a-zA-Z0-9=_\-\+/]{16,45})'''
secretGroup = 4
entropy = 3.7

[[rules]]
id = "fhir-token"
description = "FHIR Access Token"
regex = '''(?i)(fhir[_-]?token|fhir[_-]?access[_-]?token)([^a-zA-Z0-9]|$){0,1}[=:"\s'\``]{1,2}([a-zA-Z0-9=_\-\+/\.]{32,250})'''
secretGroup = 3
entropy = 3.7

[[rules]]
id = "patient-id"
description = "Patient ID Pattern"
regex = '''(?i)(patient[_-]?id|mrn|medical[_-]?record[_-]?number)([^a-zA-Z0-9]|$){0,1}[=:"\s'\``]{1,2}([A-Z0-9]{6,15})'''
secretGroup = 3
entropy = 2.5

[[rules]]
id = "phi-data"
description = "PHI Data Pattern"
regex = '''(?i)(ssn|social[_-]?security|dob|date[_-]?of[_-]?birth)([^a-zA-Z0-9]|$){0,1}[=:"\s'\``]{1,2}([0-9\-]{9,11})'''
secretGroup = 3
entropy = 2.5

[[rules]]
id = "oauth-credentials"
description = "OAuth Client Credentials"
regex = '''(?i)(client[_-]?id|client[_-]?secret)([^a-zA-Z0-9]|$){0,1}[=:"\s'\``]{1,2}([a-zA-Z0-9\-_\.]{16,64})'''
secretGroup = 3
entropy = 3.5

[[rules]]
id = "jwt-token"
description = "JWT Token"
regex = '''(?i)(jwt[_-]?token|bearer)([^a-zA-Z0-9]|$){0,1}[=:"\s'\``]{1,2}([a-zA-Z0-9\-_\.]{64,})'''
secretGroup = 3
entropy = 3.7

# Additional security rules
[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN ((RSA|DSA|EC|PGP) )?PRIVATE KEY( BLOCK)?-----'''
secretGroup = 0
entropy = 0.0

[[rules]]
id = "encryption-key"
description = "Encryption Key"
regex = '''(?i)(encryption[_-]?key|cipher[_-]?key)([^a-zA-Z0-9]|$){0,1}[=:"\s'\``]{1,2}([a-zA-Z0-9=_\-\+/]{16,45})'''
secretGroup = 3
entropy = 3.7

# Global settings
[global]
showsecrets = false
useregex = true
verbosity = 3
