version: 0.1
cli:
  version: 1.17.2
plugins:
  sources:
    - id: trunk
      ref: v1.2.6
      uri: https://github.com/trunk-io/plugins
lint:
  ignore:
    - linters: [actionlint/property-environment]
      paths:
        - .github/workflows/*.yml
        - .specstory/
        - node_modules/
