# Prettier friendly markdownlint config (all formatting rules disabled)
extends: markdownlint/style/prettier

# Default state for all rules
default: true

# Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# Trailing whitespace
MD009:
  br_spaces: 2 # Trailing spaces for line breaks

# Inline HTML
MD033: false # Allow inline HTML

# Allow emphasis with underscore
MD036: false

# First line in a file should be a top-level heading
MD041: false

# Disable specific rules for MDX files
MD001: false # heading-increment
MD002: false # first-heading-h1
MD007: false # ul-indent
MD010: false # no-hard-tabs
MD027: false # no-multiple-space-blockquote
MD046: false # code-block-style
