# Gitleaks configuration file

[allowlist]
description = "Allowlist for test files and mock data"
paths = [
    '''src/tests/crypto\.test\.ts''',
]

regexes = [
    '''test-encryption-key-[0-9]+''',
    '''wrong-key-[0-9]+''',
]

# Test files containing mock keys
[allowlist.test_files]
description = "Test files with mock keys"
paths = [
    '''.*test\.ts$''',
    '''.*spec\.ts$''',
] 