var parse__tfm_8py = [
  [
    'parse_tfm.CharInfoWord',
    'classparse__tfm_1_1_char_info_word.html',
    'classparse__tfm_1_1_char_info_word',
  ],
  [
    'parse_tfm.LigKernProgram',
    'classparse__tfm_1_1_lig_kern_program.html',
    'classparse__tfm_1_1_lig_kern_program',
  ],
  [
    'parse_tfm.TfmCharMetrics',
    'classparse__tfm_1_1_tfm_char_metrics.html',
    'classparse__tfm_1_1_tfm_char_metrics',
  ],
  [
    'parse_tfm.TfmFile',
    'classparse__tfm_1_1_tfm_file.html',
    'classparse__tfm_1_1_tfm_file',
  ],
  [
    'parse_tfm.TfmReader',
    'classparse__tfm_1_1_tfm_reader.html',
    'classparse__tfm_1_1_tfm_reader',
  ],
  [
    'parse_tfm.read_tfm_file',
    'namespaceparse__tfm.html#a7d902304b75e06094a23ad75990c9d6f',
    null,
  ],
]
