/**
 * MOCK CONVEX API
 * This file is a placeholder for the generated Convex API types.
 * In a real project, this file would be generated by the Convex CLI.
 */

// Define a mock API structure that matches what's expected in the application
export const api = {
  metrics: {
    getActiveUsers: { path: 'metrics.getActiveUsers' },
    getActiveSessions: { path: 'metrics.getActiveSessions' },
    getAverageResponseTime: { path: 'metrics.getAverageResponseTime' },
    getSystemLoad: { path: 'metrics.getSystemLoad' },
    getStorageUsed: { path: 'metrics.getStorageUsed' },
    getMessagesSent: { path: 'metrics.getMessagesSent' },
    getActiveSecurityLevel: { path: 'metrics.getActiveSecurityLevel' },
  },
  users: {
    getUser: { path: 'users.getUser' },
    listUsers: { path: 'users.listUsers' },
    createUser: { path: 'users.createUser' },
  },
  messages: {
    send: { path: 'messages.send' },
    list: { path: 'messages.list' },
    getByThread: { path: 'messages.getByThread' },
  },
}
