
from typing import Any, Optional

def load_environment() -> None: ...
def encode_image_file(image_path: str) -> tuple[str, str]: ...
def create_llm_client(provider: str = "openai") -> Any: ...
def query_llm(
    prompt: str,
    client: Optional[Any] = None,
    model: Optional[str] = None,
    provider: str = "openai",
    image_path: Optional[str] = None,
) -> Optional[str]: ...
def main() -> None: ...
