name: Database Backup

on:
  schedule:
    - cron: 0 */12 * * * # Run every 12 hours
  workflow_dispatch: {} # Allow manual trigger without inputs

permissions:
  contents: write

env:
  NODE_VERSION: 22.11.0
  PNPM_VERSION: 10.0.0
  BACKUP_RETENTION_DAYS: 30
  BACKUP_DIR: ./backups

jobs:
  backup:
    name: >-
      Backup ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }} Database
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Supabase CLI
        uses: supabase/setup-cli@v1.1.0
        with:
          version: latest

      - name: Login to Supabase
        run: supabase login --access-token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create backup directory
        run: mkdir -p ${{ env.BACKUP_DIR }}

      - name: Create backup
        id: backup
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          PGHOST: ${{ secrets.SUPABASE_DB_HOST }}
          PGUSER: ${{ secrets.SUPABASE_DB_USER }}
          PGDATABASE: ${{ secrets.SUPABASE_DB_NAME }}
          ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
        run: |
          set -euo pipefail

          timestamp=$(date +%Y%m%d_%H%M%S)
          backup_file="supabase_backup_${ENVIRONMENT}_${timestamp}.sql"
          compressed_file="${backup_file}.gz"

          echo "::group::Creating database backup"
          # Create backup with error handling
          if ! pg_dump -p 5432 -F p > "${BACKUP_DIR}/${backup_file}"; then
            echo "::error::Failed to create database backup"
            exit 1
          fi

          # Verify backup size
          if [ ! -s "${BACKUP_DIR}/${backup_file}" ]; then
            echo "::error::Backup file is empty"
            exit 1
          fi
          echo "::endgroup::"

          echo "::group::Compressing backup"
          if ! gzip "${BACKUP_DIR}/${backup_file}"; then
            echo "::error::Failed to compress backup file"
            exit 1
          fi
          echo "::endgroup::"

          # Set outputs for next steps
          echo "environment=${ENVIRONMENT}" >> $GITHUB_OUTPUT
          echo "timestamp=${timestamp}" >> $GITHUB_OUTPUT

      - name: Commit and push backup
        if: success()
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add ${{ env.BACKUP_DIR }}
          git commit -m "Backup database: ${{ steps.backup.outputs.environment }} - ${{ steps.backup.outputs.timestamp }}"
          git push

      - name: Clean old backups
        if: success()
        run: |
          set -euo pipefail
          echo "::group::Cleaning old backups"
          find ${{ env.BACKUP_DIR }} -name "*.sql.gz" -type f -mtime +${{ env.BACKUP_RETENTION_DAYS }} -delete
          echo "::endgroup::"

      - name: Notify status
        if: always()
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          payload: |
            {
              "text": "${{ job.status == 'success' && '✅' || '🚨' }} Database Backup Status",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Status:* ${{ job.status == 'success' && '✅ Success' || '🚨 Failure' }}"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Environment:* ${{ steps.backup.outputs.environment }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Timestamp:* ${{ steps.backup.outputs.timestamp }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow:* ${{ github.workflow }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Trigger:* ${{ github.event_name }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>"
                  }
                }
              ]
            }
