name: GitHub Backup to Dropbox

on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sunday at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  backup:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # timeout after 60 minutes

    steps:
      - name: Backup GitHub to Dropbox
        uses: chyroc/github2dropbox@v0.4.0
        with:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }} # Use your personal access token stored as G_TOKEN
          ENABLE_REPO: true
          ENABLE_STAR: true
          ENABLE_FOLLOWER: true
          ENABLE_FOLLOWING: true
          ENABLE_GIST: true
          ENABLE_ISSUE: true
          ENABLE_ISSUE_COMMENT: true
          ENABLE_REPO_GIT: true
          DROPBOX_PATH: 'GitHub-Backup' # Optional: customize the backup folder path in Dropbox
