name: Deployment Rollback

on:
  push:
    branches:
      - main
      - staging

permissions:
  contents: read
  id-token: write

env:
  NODE_VERSION: 20.11.0
  PNPM_VERSION: 10.0.0

jobs:
  rollback-staging:
    name: Rollback Staging
    runs-on: ubuntu-latest
    environment: staging
    if: github.ref == 'refs/heads/staging'
    concurrency:
      group: staging_environment
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine rollback tag
        id: get-tag
        run: |
          TAGS=$(git tag -l "staging-*" --sort=-committerdate)
          TAG_COUNT=$(echo "$TAGS" | grep -v "^$" | wc -l)

          if [ "$TAG_COUNT" -eq 0 ]; then
            echo "::error::No staging tags found"
            exit 1
          elif [ "$TAG_COUNT" -eq 1 ]; then
            echo "::error::Only one staging tag exists"
            exit 1
          fi

          TAG=$(echo "$TAGS" | sed -n '2p')
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Rolling back to: $TAG"
          git checkout $TAG
        shell: /usr/bin/bash -e {0}
        env:
          NODE_VERSION: ${{ env.NODE_VERSION }}
          PNPM_VERSION: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm build

      - name: Deploy rollback
        run: |
          npm install -g wrangler
          wrangler pages deploy dist --project-name=gradiant-astro --branch=staging

      - name: Create rollback tag
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          git tag rollback-staging-$TIMESTAMP
          git push origin rollback-staging-$TIMESTAMP

  rollback-production:
    name: Rollback Production
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: production_environment
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine rollback tag
        id: get-tag
        run: |
          TAGS=$(git tag -l "production-*" --sort=-committerdate)
          TAG_COUNT=$(echo "$TAGS" | grep -v "^$" | wc -l)

          if [ "$TAG_COUNT" -eq 0 ]; then
            echo "::error::No production tags found"
            exit 1
          elif [ "$TAG_COUNT" -eq 1 ]; then
            echo "::error::Only one production tag exists"
            exit 1
          fi

          TAG=$(echo "$TAGS" | sed -n '2p')
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Rolling back to: $TAG"
          git checkout $TAG
        shell: /usr/bin/bash -e {0}
        env:
          NODE_VERSION: ${{ env.NODE_VERSION }}
          PNPM_VERSION: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm build

      - name: Deploy rollback
        run: |
          npm install -g wrangler
          wrangler pages deploy dist --project-name=gradiant-astro --branch=production

      - name: Create rollback tag
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          git tag rollback-production-$TIMESTAMP
          git push origin rollback-production-$TIMESTAMP
